services:
  app:
    image: serversideup/php:8.2-fpm-nginx
    container_name: lumen_app
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    environment:
      - SERVICE_URL_APP_8080
      - APP_NAME=Lumen
      - APP_ENV=production
      - APP_DEBUG=false
      - 'APP_URL=${SERVICE_URL_APP}'
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - LOG_CHANNEL=stack
      - APP_TIMEZONE=UTC
      - 'APP_KEY=${SERVICE_BASE64_64_KEY}'
      # CONFIG
      - PHP_OPCACHE_ENABLE=1
      - AUTORUN_ENABLED=true
      - AUTORUN_LARAVEL_STORAGE_LINK=true
